import type { Question } from '@harness/quiz';

// Two small failure diagnoses per core domain.
const q = (domain: string, code: string, ask: string, choices: string[], answer: number, why: string): Question =>
  ({ domain, code, ask, choices, answer, why });

export const questions: Question[] = [
  q('math', 'const angle = Math.acos(a.dot(b));\n// both inputs are approximately unit length',
    'A nearly identical pair sometimes produces NaN. What check catches the bug?',
    ['Assert the angle is always positive', 'Assert the angle is finite for a dot slightly above 1', 'Assert the input objects are the same instance'], 1,
    'Rounding can push a nominally unit dot outside the acos domain; clamp it before acos.'),
  q('math', 'function alongRail(v: Vector3, axis: Vector3) { return v.projectOnVector(axis); }',
    'Later code sees v changed. What is the repair?',
    ['Normalize axis after projecting', 'Replace projectOnVector with dot', 'Project a clone of v'], 2,
    'Vector3.projectOnVector mutates its receiver. A check should preserve the original input.'),

  q('transforms', 'part.position.set(4, 0, 0);\nconst hit = raycaster.intersectObject(part);',
    'The ray still hits the old position in the same tick. What is missing?',
    ['A new material', 'An updated world matrix before the raycast', 'A second camera'], 1,
    'The raycaster reads matrixWorld; update it after changing the transform.'),
  q('transforms', 'parent.scale.set(3, 1, 1);\nmesh.updateWorldMatrix(true, false);\nconst worldNormal = localNormal.clone().transformDirection(mesh.matrixWorld);',
    'The normal tilts away from a sloped face. What invariant should the check use?',
    ['Perpendicular to both transformed face edges', 'Equal X and Y components', 'Length equal to the longest edge'], 0,
    'An inverse-transpose normal matrix preserves perpendicularity under uneven scale.'),

  q('rotation', 'model.rotation.x = -Math.PI / 2;\nmodel.rotation.y += delta; // intended world-up spin',
    'Why does the model tip on some orientations?',
    ['Quaternions always stretch meshes', 'The camera up vector changed', 'Euler order makes the Y turn occur in a rotated frame'], 2,
    'Use a world-space parent turn or an intentional order; the second Euler edit is not automatically world-up.'),
  q('rotation', '// object has no parent\nconst delta = new Quaternion().setFromAxisAngle(worldY, 0.2);\nobject.quaternion.multiply(delta);',
    'The turn follows the object axis instead of world Y. What changes?',
    ['Negate all quaternion components', 'Convert delta to Euler degrees', 'Premultiply delta'], 2,
    'For an unparented object, premultiplication applies the incremental rotation in the world frame.'),

  q('camera', 'const ndc = point.clone().project(camera);\nlabel.hidden = Math.abs(ndc.x) > 1 || Math.abs(ndc.y) > 1;',
    'A label appears for a point behind the camera. What was omitted?',
    ['A brighter material', 'A front/depth check', 'An orthographic camera'], 1,
    'X and Y alone do not establish that the point is in front and within the depth range.'),
  q('camera', 'camera.near = 0.0001; camera.far = 100000; camera.updateProjectionMatrix();',
    'Coplanar surfaces flicker. Which experiment tests the likely cause?',
    ['Tighten near/far and compare depth stability', 'Double the pixel ratio', 'Turn off color management'], 0,
    'A huge depth range, especially a tiny near plane, wastes depth precision.'),

  q('geometry', 'geometry.applyMatrix4(new Matrix4().makeScale(-1, 1, 1));\n// front faces disappear',
    'Which data changed meaning?',
    ['Triangle winding', 'Texture color space', 'Vertex count'], 0,
    'A negative determinant reverses handedness; baked triangle order needs correction.'),
  q('geometry', 'position.setXYZ(0, 0, 1, 0);\ngeometry.computeVertexNormals();\n// GPU still shows old shape',
    'Which missing step is most direct?',
    ['Set mesh.visible = false', 'Rebuild the renderer', 'Set position.needsUpdate = true'], 2,
    'Editing a typed attribute on the CPU requires an upload flag for the GPU buffer.'),

  q('assets', 'await loader.loadAsync(url);\n// first visible frame still hitches',
    'Which work may remain after loading?',
    ['Only URL parsing', 'GPU upload and shader compilation', 'Only pointer capture'], 1,
    'Decoded assets may still incur first-use GPU work; compare a warm-up frame.'),
  q('assets', 'scene.remove(oldPart);\noldPart.material.map.dispose();\n// newPart uses the same map',
    'What is the ownership bug?',
    ['Removing a scene child also removes newPart', 'A shared texture was disposed while still in use', 'Textures cannot be disposed'], 1,
    'Disposal follows ownership, not removal of one object. Track remaining users.'),

  q('scene-graph', 'const copy = original.clone(true);\ncopy.children[0].material.color.set("red");',
    'The original also turns red. Which shared object explains it?',
    ['The new child Object3D', 'The copied root position', 'The material'], 2,
    'Object3D.clone makes new nodes but retains geometry and material references.'),
  q('scene-graph', 'const box = new Box3().setFromObject(product);\n// product has a helper child far from the part',
    'Why does camera fit pull too far back?',
    ['The helper is included in descendant bounds', 'Box3 ignores child meshes', 'A camera fit must use local bounds'], 0,
    'Inspect the tree and include only intended visible product geometry in the fit bounds.'),

  q('queries', 'const normal = hit.face!.normal.clone();\nmarker.quaternion.setFromUnitVectors(up, normal);\n// mesh is rotated',
    'Why does the marker lean?',
    ['Raycaster normals are always zero', 'Quaternion inputs must be positions', 'The face normal is local and was used as world space'], 2,
    'Transform the local face normal to world space with the world normal matrix.'),
  q('queries', 'raycaster.setFromCamera(new Vector2(event.clientX, event.clientY), camera);',
    'Selection is wrong except near the canvas center. Which check catches it?',
    ['Convert client pixels to canvas NDC, including canvas offset', 'Use camera.position as both NDC values', 'Normalize the ray direction twice'], 0,
    'setFromCamera expects coordinates from -1 to 1 relative to the canvas.'),

  q('interaction', 'function onMove(event: PointerEvent) { drag(event); }\n// pointer leaves the canvas mid-drag',
    'Which missing step keeps the drag receiving events?',
    ['A higher DPR', 'setPointerCapture on pointer-down', 'A cloned drag plane'], 1,
    'Pointer capture routes that pointer to the canvas until release or cancellation.'),
  q('interaction', 'part.position.lerp(target, 0.1);\n// called once per frame',
    'Why does motion differ between 60 and 120 Hz?',
    ['The fixed fraction is applied twice as often per second', 'The target changes coordinate space', 'Raycaster precision halves'], 0,
    'Use a delta-time-derived fraction to make the time constant independent of frame count.'),

  q('gpu', 'const t0 = performance.now(); renderer.render(scene, camera); const ms = performance.now() - t0;',
    'Why can ms stay low during an obvious GPU bottleneck?',
    ['performance.now ignores JavaScript', 'The call may return before GPU work completes', 'render draws only visible UI'], 1,
    'CPU submission time is not a GPU timer; profile the GPU work separately.'),
  q('gpu', 'renderer.readRenderTargetPixels(target, x, y, 1, 1, pixel);\n// hover stalls',
    'Which change directly addresses the synchronization point?',
    ['Read a wider rectangle', 'Increase mesh triangle count', 'Use asynchronous render-target readback'], 2,
    'A synchronous pixel read can wait for earlier GPU commands; async readback avoids that main-thread block.'),

  q('materials', 'normalMap.colorSpace = SRGBColorSpace;\n// normals look swollen',
    'What is the data error?',
    ['The environment map is too bright', 'Metalness must be 1', 'Normal components were treated as display colors'], 2,
    'Normal maps store vectors, so sRGB decoding changes their values.'),
  q('materials', 'scene.background = hdrTexture;\nchrome.metalness = 1;\n// chrome is nearly black',
    'Which scene property should be inspected?',
    ['scene.fog', 'scene.environment', 'camera.aspect'], 1,
    'A visible background does not automatically provide image-based lighting for metal.'),

  q('shaders', 'vNormal = normalize(normalMatrix * normal);\n// output is compared with a world arrow',
    'Why do the directions disagree as the camera moves?',
    ['normalMatrix always removes scale', 'The fragment shader runs before vertices', 'normalMatrix here produces view-space normals'], 2,
    'Compare values in the same space; a world normal requires a world normal matrix.'),
  q('shaders', 'float roughness = texture2D(packedMap, uv).r;\n// roughness debug view looks metallic',
    'Which channel is likely intended?',
    ['Green', 'Red', 'Alpha'], 0,
    'In a standard packed metallic-roughness map, green is roughness and blue is metalness.'),

  q('debugging', 'if (material.color.getHex() === 0) return "material";\nif (!scene.getObjectById(mesh.id)) return "scene";',
    'What is wrong with this black-screen triage?',
    ['getObjectById always throws', 'Black materials are never valid', 'It blames appearance before proving the object is in the scene'], 2,
    'Check the earliest failed stage first; material properties cannot explain a missing draw.'),
  q('debugging', 'const world = local.clone().applyMatrix4(mesh.matrixWorld);\n// local contains NaN',
    'Which guard should a regression check require?',
    ['Reject or replace non-finite input before transform', 'Always set mesh.visible = false', 'Read only the X coordinate'], 0,
    'A non-finite component spreads through matrix operations and can corrupt helper geometry.'),

  q('optimization', 'renderer.setPixelRatio(window.devicePixelRatio);\n// phone reports DPR 4',
    'Which comparison proves the pixel-cost concern?',
    ['Compare CSS width alone', 'Compare drawing-buffer pixels at DPR 4 and capped DPR 2', 'Compare scene child count'], 1,
    'Doubling DPR on both axes quadruples the pixel count; a cap can bound it.'),
  q('optimization', 'swapVariant();\n// renderer.info.memory.textures rises after each complete swap cycle',
    'What should a leak check assert?',
    ['Counts settle near baseline after repeated swaps', 'Counts increase exactly once per frame', 'All geometries have unique names'], 0,
    'A bounded repeated cycle should release retired textures; steady growth indicates retained GPU resources.'),
];
