import { answered } from '@harness/check';
import * as THREE from 'three';
import { expect, it, vi } from 'vitest';
import { aaWireGrid } from './drill';
it('draws bright grid lines and dark cell interiors', () => {
 const errors=vi.spyOn(console,'error');
 const renderer=new THREE.WebGLRenderer({antialias:false}); renderer.setSize(64,64);
 const geometry=new THREE.PlaneGeometry(2,2), material=answered(aaWireGrid());
 const scene=new THREE.Scene(); scene.add(new THREE.Mesh(geometry,material));
 const camera=new THREE.PerspectiveCamera(60,1,.1,10); camera.position.z=2;
 const target=new THREE.WebGLRenderTarget(64,64); renderer.setRenderTarget(target); renderer.render(scene,camera);
 const line=new Uint8Array(4), interior=new Uint8Array(4);
 renderer.readRenderTargetPixels(target,32,32,1,1,line);
 renderer.readRenderTargetPixels(target,36,36,1,1,interior);
 expect(line[3]).toBe(255);
 expect(interior[3]).toBe(255);
 expect(line[0]).toBeGreaterThan(interior[0] + 100);
 expect(errors.mock.calls.flat().join(' ')).not.toMatch(/THREE.WebGLProgram: Shader Error|VALIDATE_STATUS false/);
 errors.mockRestore(); target.dispose(); geometry.dispose(); material.dispose(); renderer.dispose();
});
