import type { Question } from '@harness/quiz';

// One judgment check per core domain. The viewer records misses by domain; there is no pass bar.
export const questions: Question[] = [
  {
    domain: 'math',
    code: "const motion = new Vector3(2, 1, 0);\nconst railAxisWorld = new Vector3(1, 1, 0).normalize();",
    ask: "Which code keeps only motion along the rotated rail?",
    choices: ["motion.clone().projectOnVector(railAxisWorld)","motion.clone().setY(0)","motion.clone().normalize()"],
    answer: 0,
    why: "Projection keeps the component along a direction at any angle. Zeroing Y only works for a world-aligned rail.",
  },
  {
    domain: 'transforms',
    code: "const localNormal = hit.face.normal;\nmesh.parent.scale.set(3, 1, 1);",
    ask: "What should turn this face normal into a world normal?",
    choices: ["A normal matrix built from mesh.matrixWorld","mesh.normalMatrix, used without updating","mesh.matrixWorld through transformDirection"],
    answer: 0,
    why: "Uneven scale needs the inverse-transpose normal matrix built from the mesh's world matrix.",
  },
  {
    domain: 'rotation',
    code: "// delta turns around the world's Y axis\nconst delta = new Quaternion().setFromAxisAngle(yAxis, 0.2);",
    ask: "How should the delta combine with the current object turn?",
    choices: ["Premultiply: delta * current","Multiply: current * delta","Add the four quaternion components"],
    answer: 0,
    why: "A world-space delta goes before the current turn. Reversing the multiplication applies it in the object's frame.",
  },
  {
    domain: 'camera',
    code: "const ndc = point.clone().project(camera);\nconst onCanvas = Math.abs(ndc.x) <= 1 && Math.abs(ndc.y) <= 1;",
    ask: "Is onCanvas enough to show the label?",
    choices: ["No; also reject points behind the camera and outside depth","Yes; x and y contain all visibility information","No; only a raycast can decide whether it is in front"],
    answer: 0,
    why: "A point behind the camera can project inside the x and y range. Check camera-space depth or the projected depth too.",
  },
  {
    domain: 'geometry',
    code: "const left = rightGeometry.clone().applyMatrix4(new Matrix4().makeScale(-1, 1, 1));",
    ask: "Why might the left part disappear from the front?",
    choices: ["The mirror reversed triangle winding","The geometry lost all its UV coordinates","The material became transparent"],
    answer: 0,
    why: "A negative determinant flips handedness. When baked into vertex data, reverse winding to keep the front facing outward.",
  },
  {
    domain: 'assets',
    code: "scene.remove(oldFinish);\nnewPart.material.map = oldFinish.material.map;",
    ask: "What should happen before disposing the old finish?",
    choices: ["Keep the shared map alive while newPart still uses it","Dispose every resource reachable from oldFinish","Only dispose the mesh object; GPU resources follow automatically"],
    answer: 0,
    why: "Removing an object does not dispose its resources, and disposing a shared texture breaks the new user.",
  },
  {
    domain: 'scene-graph',
    code: "const box = new Box3().setFromObject(product);\n// product has a rotated child and a hidden helper",
    ask: "What should a camera-fit review check?",
    choices: ["World matrices, loose rotated bounds, and included helper children","Only product.geometry.boundingBox","Only the visible material count"],
    answer: 0,
    why: "setFromObject covers descendants, including helpers, and may be loose under rotation. Update matrices and request precise bounds when needed.",
  },
  {
    domain: 'queries',
    code: "// A million-triangle mesh is selectable\nconst hits = raycaster.intersectObject(mesh);",
    ask: "Which comparison can justify a GPU picking pass?",
    choices: ["Measure CPU raycast cost against a GPU ID pass and async readback","Assume GPU picking is always faster","Use synchronous readback because one pixel is free"],
    answer: 0,
    why: "The choice depends on measured CPU traversal, GPU pass cost, and readback. Async readback avoids blocking the main thread.",
  },
  {
    domain: 'interaction',
    code: "const hit = pointerRay.intersectPlane(dragPlane, new Vector3());\n// the object was grabbed away from its origin",
    ask: "Where should the object origin go?",
    choices: ["hit plus the saved origin-to-grab offset","Exactly at hit","At hit after zeroing its Y coordinate"],
    answer: 0,
    why: "The offset from the grabbed point to the origin keeps the part from snapping under the pointer.",
  },
  {
    domain: 'gpu',
    code: "const start = performance.now();\nrenderer.render(scene, camera);\nconst cpuMs = performance.now() - start;",
    ask: "What does cpuMs establish?",
    choices: ["CPU time to submit render work, not the whole GPU frame","Exact GPU shader time","Total GPU memory in milliseconds"],
    answer: 0,
    why: "The GPU can still be working after render returns. Use a GPU timer or profiler for GPU work.",
  },
  {
    domain: 'materials',
    code: "scene.background = roomTexture;\nchrome.metalness = 1;",
    ask: "Why can the chrome still look black?",
    choices: ["The scene may lack an environment map for reflections","A metal surface must have metalness zero","Background automatically lights all materials"],
    answer: 0,
    why: "The background image and environment lighting are separate settings. A metal needs something to reflect.",
  },
  {
    domain: 'shaders',
    code: "// in a vertex shader\nvNormal = normalize(normalMatrix * normal);",
    ask: "What does this debug color track?",
    choices: ["A view-space normal that changes as the camera moves","A world-space normal fixed to the scene","The triangle's UV coordinates"],
    answer: 0,
    why: "The built-in normalMatrix takes normals into view space. Use a world normal matrix for a world-space debug view.",
  },
  {
    domain: 'debugging',
    code: "// Product is black after a material edit\n// Geometry is still in the frustum",
    ask: "What is the first useful isolation step?",
    choices: ["Try a simple known material, then inspect lights and maps","Rewrite the fragment shader immediately","Raise the camera far plane without checking anything"],
    answer: 0,
    why: "A known material helps separate material and lighting faults from geometry and camera faults.",
  },
  {
    domain: 'optimization',
    code: "renderer.setPixelRatio(3);\n// CSS canvas is 400 by 800",
    ask: "How many physical pixels does this request before any cap?",
    choices: ["About 2.88 million","About 960 thousand","About 320 thousand"],
    answer: 0,
    why: "Pixel count grows with DPR squared: 400 × 800 × 3 × 3 = 2.88 million.",
  },
];
