import type { Question } from '@harness/quiz';

// Two judgment checks per core domain. The viewer records misses by domain; there is no pass bar.
export const questions: Question[] = [
  {
    domain: 'math',
    code: "const motion = new Vector3(2, 1, 0);\nconst railAxisWorld = new Vector3(1, 1, 0).normalize();",
    ask: "Which code keeps only motion along the rotated rail?",
    choices: ["motion.clone().projectOnVector(new Vector3(1, 0, 0))", "motion.clone().projectOnVector(railAxisWorld)", "motion.clone().setY(0).normalize()"],
    answer: 1,
    why: "Projection keeps the component along a direction at any angle. Zeroing Y only works for a world-aligned rail.",
  },
  {
    domain: 'transforms',
    code: "const localNormal = hit.face.normal;\nmesh.parent.scale.set(3, 1, 1);",
    ask: "What should turn this face normal into a world normal?",
    choices: ["A normal matrix built from mesh.matrixWorld", "mesh.normalMatrix, used without updating", "mesh.matrixWorld through transformDirection"],
    answer: 0,
    why: "Uneven scale needs the inverse-transpose normal matrix built from the mesh's world matrix.",
  },
  {
    domain: 'rotation',
    code: "// delta turns around the world's Y axis\nconst delta = new Quaternion().setFromAxisAngle(yAxis, 0.2);",
    ask: "How should the delta combine with the current object turn?",
    choices: ["Multiply: current * delta", "Add the four quaternion components", "Premultiply: delta * current"],
    answer: 2,
    why: "A world-space delta goes before the current turn. Reversing the multiplication applies it in the object's frame.",
  },
  {
    domain: 'camera',
    code: "const ndc = point.clone().project(camera);\nconst onCanvas = Math.abs(ndc.x) <= 1 && Math.abs(ndc.y) <= 1;",
    ask: "Is onCanvas enough to show the label?",
    choices: ["No; also reject points behind the camera and outside depth", "Yes; x and y contain all visibility information", "No; only a raycast can decide whether it is in front"],
    answer: 0,
    why: "A point behind the camera can project inside the x and y range. Check camera-space depth or the projected depth too.",
  },
  {
    domain: 'geometry',
    code: "const left = rightGeometry.clone().applyMatrix4(new Matrix4().makeScale(-1, 1, 1));",
    ask: "Why might the left part disappear from the front?",
    choices: ["The material became transparent", "The mirror reversed triangle winding", "The geometry lost all its UV coordinates"],
    answer: 1,
    why: "A negative determinant flips handedness. When baked into vertex data, reverse winding to keep the front facing outward.",
  },
  {
    domain: 'assets',
    code: "scene.remove(oldFinish);\nnewPart.material.map = oldFinish.material.map;",
    ask: "What should happen before disposing the old finish?",
    choices: ["Keep the shared map alive while newPart still uses it", "Dispose every resource reachable from oldFinish", "Only dispose the mesh object; GPU resources follow automatically"],
    answer: 0,
    why: "Removing an object does not dispose its resources, and disposing a shared texture breaks the new user.",
  },
  {
    domain: 'scene-graph',
    code: "const box = new Box3().setFromObject(product);\n// product has a rotated child and a hidden helper",
    ask: "What should a camera-fit review check?",
    choices: ["Only geometry.boundingBox, regardless of nested children", "Only visible children, since helpers are skipped automatically", "World matrices, rotated bounds, and helper children"],
    answer: 2,
    why: "setFromObject covers descendants, including helpers, and may be loose under rotation. Update matrices and request precise bounds when needed.",
  },
  {
    domain: 'queries',
    code: "// A million-triangle mesh is selectable\nconst hits = raycaster.intersectObject(mesh);",
    ask: "Which comparison can justify a GPU picking pass?",
    choices: ["Measure only readback, because the ID pass is free", "Measure raycast, ID pass, and async readback", "Assume GPU wins once triangles exceed one million"],
    answer: 1,
    why: "The choice depends on measured CPU traversal, GPU pass cost, and readback. Async readback avoids blocking the main thread.",
  },
  {
    domain: 'interaction',
    code: "const hit = pointerRay.intersectPlane(dragPlane, new Vector3());\n// the object was grabbed away from its origin",
    ask: "Where should the object origin go?",
    choices: ["Hit alone, so the part origin follows the cursor", "Hit with Y set to the object's starting height", "Hit plus the saved grab offset"],
    answer: 2,
    why: "The offset from the grabbed point to the origin keeps the part from snapping under the pointer.",
  },
  {
    domain: 'gpu',
    code: "const start = performance.now();\nrenderer.render(scene, camera);\nconst cpuMs = performance.now() - start;",
    ask: "What does cpuMs establish?",
    choices: ["GPU shader time, including all pixels and passes", "GPU memory transfer cost for buffers and textures", "CPU submission time, not the full GPU frame"],
    answer: 2,
    why: "The GPU can still be working after render returns. Use a GPU timer or profiler for GPU work.",
  },
  {
    domain: 'materials',
    code: "scene.background = roomTexture;\nchrome.metalness = 1;",
    ask: "Why can the chrome still look black?",
    choices: ["The scene may lack an environment map for reflections", "A metal surface must have metalness zero", "Background automatically lights all materials"],
    answer: 0,
    why: "The background image and environment lighting are separate settings. A metal needs something to reflect.",
  },
  {
    domain: 'shaders',
    code: "// in a vertex shader\nvNormal = normalize(normalMatrix * normal);",
    ask: "What does this debug color track?",
    choices: ["A world-space normal fixed to the scene", "The triangle's UV coordinates", "A view-space normal that changes as the camera moves"],
    answer: 2,
    why: "The built-in normalMatrix takes normals into view space. Use a world normal matrix for a world-space debug view.",
  },
  {
    domain: 'debugging',
    code: "// Product is black after a material edit\n// Geometry is still in the frustum",
    ask: "What is the first useful isolation step?",
    choices: ["Raise the camera far plane without checking anything", "Try a simple known material, then inspect lights and maps", "Rewrite the fragment shader immediately"],
    answer: 1,
    why: "A known material helps separate material and lighting faults from geometry and camera faults.",
  },
  {
    domain: 'optimization',
    code: "renderer.setPixelRatio(3);\n// CSS canvas is 400 by 800",
    ask: "How many physical pixels does this request before any cap?",
    choices: ["About 320 thousand", "About 2.88 million", "About 960 thousand"],
    answer: 1,
    why: "Pixel count grows with DPR squared: 400 × 800 × 3 × 3 = 2.88 million.",
  },
  {
    domain: 'math',
    code: "const n = new Vector3(0, 3, 0);\nconst motion = new Vector3(2, -1, 1);",
    ask: "Which result is motion along the wall whose normal is n?",
    choices: ["motion.clone().setY(0).normalize()", "motion.clone().projectOnVector(n)", "motion.clone().projectOnPlane(n)"],
    answer: 2,
    why: "Projecting onto the plane removes only the component along the wall normal, even when the wall is angled.",
  },
  {
    domain: 'transforms',
    code: "part.position.x = 5;\nconst world = part.matrixWorld;",
    ask: "What must happen before using world for a raycast this tick?",
    choices: ["Read part.matrix instead", "Update the part's world matrix", "Set part.matrixAutoUpdate to false"],
    answer: 1,
    why: "A position edit does not immediately rewrite matrixWorld. Update it before same-tick queries.",
  },
  {
    domain: 'rotation',
    code: "camera.up.set(0, 0, 1);\ncamera.lookAt(target);",
    ask: "What does changing up affect?",
    choices: ["The camera's near and far clip planes", "Which way the camera rolls around its view direction", "The target's distance from the camera"],
    answer: 1,
    why: "lookAt uses the up direction to choose roll while aiming toward the target.",
  },
  {
    domain: 'camera',
    code: "// Same 24-pixel label at depths 2 and 8\nconst depth = 8;",
    ask: "How should its world height change farther from a perspective camera?",
    choices: ["Shrink with depth to avoid clipping", "Stay equal because CSS pixels are constant", "Grow with depth so it still covers 24 pixels"],
    answer: 2,
    why: "At greater depth, one screen pixel spans more world space, so the world-size label grows.",
  },
  {
    domain: 'geometry',
    code: "const position = geometry.getAttribute('position'); // itemSize 3\nposition.array[9] = 1;",
    ask: "Which value changed?",
    choices: ["X of vertex 3", "Z of vertex 9", "X of vertex 9"],
    answer: 0,
    why: "An XYZ attribute stores three numbers per vertex; array slot 9 is vertex 3's X.",
  },
  {
    domain: 'assets',
    code: "// A variant was decoded, but has never been drawn\nswitchToVariant();",
    ask: "Which first-use work can still hitch?",
    choices: ["Only network download", "Only JavaScript object construction", "Texture upload and shader compile"],
    answer: 2,
    why: "Decoded CPU data may still need GPU upload and a shader program on first draw.",
  },
  {
    domain: 'scene-graph',
    code: "const copy = product.clone(true);\n// product meshes share geometry and materials",
    ask: "What does the deep object clone share?",
    choices: ["Shared geometry and materials; new objects", "New geometry, material, and object copies at every child", "The same child objects, just under a new root"],
    answer: 0,
    why: "clone(true) creates new objects and children, but geometry and material references remain shared.",
  },
  {
    domain: 'queries',
    code: "const ray = new Ray(new Vector3(0, 2, 0), new Vector3(1, 0, 0));\nconst floor = new Plane(new Vector3(0, 1, 0), 0);",
    ask: "What does ray.intersectPlane(floor, target) return?",
    choices: ["A distant point because infinite planes catch every ray", "Ray origin because a parallel ray hits at its start", "null; the ray is parallel and above the floor"],
    answer: 2,
    why: "The ray stays above the plane and never crosses it, so there is no hit.",
  },
  {
    domain: 'interaction',
    code: "const alpha = 0.1;\nposition.lerp(target, alpha); // once each frame",
    ask: "What changes at a different frame rate?",
    choices: ["The object's material", "The motion rate per second", "The target's coordinate space"],
    answer: 1,
    why: "A fixed per-frame fraction runs a different number of times each second. Use delta time for consistent motion.",
  },
  {
    domain: 'gpu',
    code: "renderer.readRenderTargetPixels(target, x, y, 1, 1, pixel);",
    ask: "What is a cost risk during picking?",
    choices: ["The read can stall the main thread waiting for GPU work", "The renderer skips all draw calls", "The one pixel permanently doubles GPU memory"],
    answer: 0,
    why: "Synchronous GPU readback can wait for earlier GPU work to finish. The async API can avoid blocking.",
  },
  {
    domain: 'materials',
    code: "normalMap.colorSpace = SRGBColorSpace;\n// the normal map stores directions, not display color",
    ask: "What should the reviewer change?",
    choices: ["Raise tone mapping exposure", "Keep sRGB because every texture is color", "Use a data color space for the normal map"],
    answer: 2,
    why: "Normal maps hold data values. Converting them as sRGB colors changes their directions.",
  },
  {
    domain: 'shaders',
    code: "float rough = texture2D(packedMap, uv).r;\ngl_FragColor = vec4(vec3(rough), 1.0);",
    ask: "What would a packed roughness debug view usually sample?",
    choices: ["The alpha channel after sRGB conversion", "The green channel as raw data", "The blue channel after tone mapping"],
    answer: 1,
    why: "The packed metallic-roughness convention uses green for roughness; debug it without color conversion.",
  },
  {
    domain: 'debugging',
    code: "// A sloped marker tilts after parent.scale.set(3, 1, 1)\nconst worldN = face.normal.clone().transformDirection(mesh.matrixWorld);",
    ask: "Which invariant should a check assert?",
    choices: ["The world normal stays perpendicular to both world edges", "Normal X stays zero whenever parent stretch uses X", "Marker size stays exactly one world unit under scale"],
    answer: 0,
    why: "The transformed normal must remain perpendicular to the transformed surface, which exposes the wrong direction transform.",
  },
  {
    domain: 'optimization',
    code: "// 20 finish swaps complete\nrenderer.info.memory.textures: 4 -> 24",
    ask: "What does the rising count suggest?",
    choices: ["A texture disposal leak across repeated swaps", "Proof the GPU is faster after each variant is loaded", "Expected warm-up that can grow indefinitely with use"],
    answer: 0,
    why: "After the same full cycle, texture counts should settle near a stable baseline; steady growth warrants investigation.",
  },
];
