import type { Question } from '@harness/quiz';

// Two from-memory application decisions per core domain.
const q = (domain: string, code: string, ask: string, choices: string[], answer: number, why: string): Question =>
  ({ domain, code, ask, choices, answer, why });

export const questions: Question[] = [
  q('math', 'const toTarget = target.clone().sub(origin);\nconst forward = new Vector3(0, 0, -1);',
    'Which condition says the target is in front?',
    ['forward.cross(toTarget).length() > 0', 'forward.dot(toTarget) > 0', 'forward.dot(toTarget) < 0'], 1,
    'A positive dot product means the target has a component along forward.'),
  q('math', 'const slide = new Vector3(3, 4, 0);\nconst wallNormal = new Vector3(0, 1, 0);',
    'Which result keeps only motion along the wall?',
    ['slide.clone().projectOnVector(wallNormal)', 'slide.clone().normalize()', 'slide.clone().projectOnPlane(wallNormal)'], 2,
    'Projection on the plane removes the component perpendicular to the wall.'),

  q('transforms', 'const worldPoint = new Vector3(4, 0, 2);\n// parent may be rotated and translated',
    'How do you store this as a child position?',
    ['child.position.copy(parent.worldToLocal(worldPoint.clone()))', 'child.position.copy(worldPoint)', 'child.position.copy(worldPoint).normalize()'], 0,
    'A child position is local to its parent; worldToLocal accounts for the parent transform.'),
  q('transforms', 'part.position.x += 2;\n// read part.matrixWorld in this tick',
    'What should happen before the read?',
    ['part.matrixWorld.identity()', 'part.matrixAutoUpdate = false', 'part.updateWorldMatrix(true, false)'], 2,
    'Changing position leaves matrixWorld stale until world matrices are updated.'),

  q('rotation', 'const axis = new Vector3(0, 1, 0);\nconst turn = Math.PI / 2;',
    'Which construction makes a quarter-turn quaternion?',
    ['new Quaternion().setFromAxisAngle(axis, turn)', 'new Quaternion(0, turn, 0, 1)', 'new Quaternion().set(axis.x, axis.y, axis.z, turn)'], 0,
    'setFromAxisAngle converts an axis and angle to unit quaternion components.'),
  q('rotation', 'const current = start.clone();\nconst target = end.clone();\nconst t = 0.25;',
    'Which expression interpolates orientation?',
    ['current.add(target.multiplyScalar(t))', 'current.slerp(target, t)', 'current.x += target.x * t'], 1,
    'Spherical interpolation follows the rotation path and keeps a valid orientation.'),

  q('camera', 'const ndc = worldPoint.clone().project(camera);\nconst width = canvas.clientWidth;',
    'What is the screen X coordinate within the canvas?',
    ['(ndc.x + 1) * width / 2', 'ndc.x * width', '(1 - ndc.x) * width / 2'], 0,
    'NDC X spans -1 to 1; shift to 0 to 2, then scale by half the width.'),
  q('camera', 'const radius = 2;\nconst verticalFov = camera.fov * Math.PI / 180;',
    'Which distance fits a sphere vertically, before padding?',
    ['radius * Math.sin(verticalFov / 2)', 'radius / Math.sin(verticalFov / 2)', 'radius / verticalFov'], 1,
    'The sphere radius and half-FOV form a right triangle; distance is radius divided by the sine.'),

  q('geometry', 'const position = geometry.getAttribute("position");\n// itemSize is 3',
    'Where does vertex 5 begin in the flat attribute array?',
    ['Index 5', 'Index 18', 'Index 15'], 2,
    'Each vertex occupies three numbers, so vertex 5 starts at 5 times 3.'),
  q('geometry', 'position.setXYZ(0, 0, 2, 0);\n// vertex positions changed',
    'What should be done before lit rendering?',
    ['Only set material.needsUpdate', 'Mark positions dirty and recompute vertex normals', 'Only normalize the mesh quaternion'], 1,
    'Upload the changed attribute and rebuild normals for the new surface shape.'),

  q('assets', 'const image = { width: 1024, height: 1024 };\n// RGBA8, one mip level',
    'About how much uncompressed GPU storage does this image need?',
    ['4 MiB', '1 MiB', '16 MiB'], 0,
    '1024 times 1024 times four bytes is about 4 MiB before mip levels.'),
  q('assets', 'oldPart.material.map = sharedTexture;\nnewPart.material.map = sharedTexture;\nscene.remove(oldPart);',
    'Which resource must stay alive?',
    ['oldPart geometry forever', 'Every resource attached to oldPart', 'sharedTexture while newPart uses it'], 2,
    'Texture ownership is shared here; removing one mesh does not end the other use.'),

  q('scene-graph', 'root.add(group);\ngroup.add(mesh);',
    'Which call visits root, group, and mesh?',
    ['root.children.forEach(callback)', 'root.getObjectByName("mesh")', 'root.traverse(callback)'], 2,
    'traverse includes the object and all descendants, not only direct children.'),
  q('scene-graph', 'const group = new Group();\n// rotated child meshes extend away from its origin',
    'How do you compute a world-space group box?',
    ['group.geometry.boundingBox', 'new Box3().setFromObject(group)', 'new Box3().setFromPoints([group.position])'], 1,
    'setFromObject walks descendant geometry and world transforms.'),

  q('queries', 'const rect = canvas.getBoundingClientRect();\nconst eventX = pointer.clientX;',
    'Which expression converts pointer X to NDC?',
    ['((eventX - rect.left) / rect.width) * 2 - 1', '(eventX / rect.width) * 2 - 1', '(eventX - rect.left) / rect.width'], 0,
    'Subtract the canvas left edge, normalize within its width, then map to -1 through 1.'),
  q('queries', 'const ray = raycaster.ray;\nconst floor = new Plane(new Vector3(0, 1, 0), 0);',
    'Which call returns a point on the floor, or null?',
    ['ray.intersectPlane(floor, new Vector3())', 'ray.projectOnPlane(floor)', 'raycaster.intersectObject(floor)'], 0,
    'Ray.intersectPlane finds the geometric crossing and returns null for no forward hit.'),

  q('interaction', 'const hit = ray.intersectPlane(plane, new Vector3())!;\n// a hit exists; part may have a transformed parent',
    'What should be saved at pointer-down?',
    ['part.position.clone().sub(hit)', 'hit.clone().normalize()', 'part.getWorldPosition(new Vector3()).sub(hit)'], 2,
    'Save the world origin minus world hit. Convert the resulting world position into parent space when storing it.'),
  q('interaction', 'const decay = 5;\nconst dt = clock.getDelta();',
    'Which interpolation weight is stable across frame rates?',
    ['0.1', '1 - Math.exp(-decay * dt)', 'decay * 60'], 1,
    'Exponential decay uses elapsed time, so the same time interval gives the same fraction.'),

  q('gpu', 'const bolts = Array.from({ length: 500 }, makeBolt);',
    'Which representation can collapse identical bolt draws?',
    ['500 cloned Mesh objects', 'InstancedMesh with one shared geometry and material', '500 new geometries with one material'], 1,
    'An InstancedMesh draws many transforms in one instanced submission.'),
  q('gpu', 'const glass = new Mesh(geometry, material);\n// several transparent panes overlap',
    'Which material settings are the usual starting point?',
    ['transparent: false and depthWrite: true', 'side: DoubleSide alone', 'transparent: true and depthWrite: false'], 2,
    'Transparent blending needs transparency enabled; disabling depth writes avoids hiding later panes.'),

  q('materials', 'const baseColor = new Texture();\nconst normalMap = new Texture();',
    'Which texture should use sRGB color space?',
    ['baseColor only', 'normalMap only', 'both'], 0,
    'Base color is display color; normal values are data and should not be gamma converted.'),
  q('materials', 'const chrome = new MeshStandardMaterial({ metalness: 1 });',
    'What should the scene provide so chrome has reflections?',
    ['A larger normal map', 'A higher opacity', 'An environment map'], 2,
    'Metallic response depends heavily on environment lighting and reflections.'),

  q('shaders', 'varying vec3 vNormal;\n// vertex stage has a normal attribute',
    'Which assignment passes a view-space normal to the fragment stage?',
    ['vNormal = normalize(normalMatrix * normal);', 'vNormal = position;', 'vNormal = projectionMatrix * normal;'], 0,
    'normalMatrix converts object normals into view space for lighting or display.'),
  q('shaders', 'uniform sampler2D packedMap;\n// roughness is packed in G',
    'Which sample reads roughness?',
    ['texture2D(packedMap, uv).r', 'texture2D(packedMap, uv).g', 'texture2D(packedMap, uv).a'], 1,
    'The packed metallic-roughness convention stores roughness in green.'),

  q('debugging', 'const probe = { inScene: false, inView: false, shaderLinked: false };',
    'Which failure should a black-screen triage check first?',
    ['Scene membership', 'Shader link', 'Material roughness'], 0,
    'An object absent from the scene cannot be rendered regardless of later stages.'),
  q('debugging', 'renderer.render(scene, camera);\nconst counts = renderer.info.render;',
    'What can counts reveal?',
    ['Exact GPU shader time', 'Draw calls and triangles for this frame', 'All material allocations'], 1,
    'The render counters record submitted work, not a GPU timer or ownership history.'),

  q('optimization', 'const cssWidth = 400;\nconst cssHeight = 300;\nconst dpr = 3;',
    'How many drawing-buffer pixels does uncapped DPR request?',
    ['360,000', '120,000', '1,080,000'], 2,
    'Width and height both scale by DPR, so pixel work grows with DPR squared.'),
  q('optimization', 'function animate() { renderer.render(scene, camera); requestAnimationFrame(animate); }\n// scene is static',
    'What saves idle frame work?',
    ['Increase antialiasing', 'Clone geometry per frame', 'Render when state changes'], 2,
    'A static scene needs a frame only after an input, resize, or other visible change.'),
];
